<?php

declare(strict_types=1);

# Generated by the protocol buffer compiler (for Phluxor). DO NOT EDIT!
# source: simple/simple.proto

namespace TestSimple;

use Phluxor\GRPC;

interface SimpleServiceInterface extends GRPC\ServiceInterface
{
    // GRPC specific service name.
    public const NAME = "testSimple.SimpleService";

    /**
    * @param GRPC\ContextInterface $ctx
    * @param SimpleMessage $in
    * @return SimpleMessage
    *
    * @throws GRPC\Exception\InvokeException
    */
    public function SimpleMethod(GRPC\ContextInterface $ctx, SimpleMessage $in): SimpleMessage;
}
